import type { Metadata } from "next";
import { Anek_Malayalam, Inter,Bungee ,Raleway} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const RalewayFont = Raleway({
  subsets: ['latin'],
  display:"swap",
  variable: "--font-raleway",
  weight: [ '400',"600","300","800","800","900","300","500","700"],
});

export const metadata: Metadata = {
  title: "Mihrab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body        className={` ${RalewayFont.variable}  antialiased`}
>{children}</body>
    </html>
  );
}
